#!/usr/bin/env python3
"""Build xai/config/forecaster_profile.json from patient CSV or JSON export."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from forecaster import ArrivalForecaster, default_profile_path  # noqa: E402


def load_records_from_csv(csv_path: Path) -> list[dict]:
    df = pd.read_csv(csv_path)
    time_col = "admissionTime" if "admissionTime" in df.columns else "arrival_time"
    priority_col = "priority" if "priority" in df.columns else "triage_level"
    records = []
    for row in df.itertuples(index=False):
        row_dict = row._asdict()
        records.append(
            {
                "admissionTime": row_dict.get(time_col),
                "priority": row_dict.get(priority_col),
            }
        )
    return records


def calibrate_thresholds(forecaster: ArrivalForecaster, steps: int = 961) -> dict[str, float]:
    from datetime import datetime, timedelta, timezone

    start = datetime(2026, 3, 1, 7, 0, tzinfo=timezone.utc)
    loads, crits = [], []
    for step in range(steps):
        current = start + timedelta(hours=step)
        load, crit = forecaster.predict(current)
        loads.append(load)
        crits.append(crit)

    load_thresh = float(np.percentile(loads, 75))
    crit_thresh = float(np.percentile(crits, 75))
    n_surge = sum(1 for load, crit in zip(loads, crits) if load > load_thresh and crit > crit_thresh)
    if n_surge == 0:
        load_thresh = float(np.percentile(loads, 50))
        crit_thresh = float(np.percentile(crits, 50))

    return {"load": round(load_thresh, 4), "crit": round(crit_thresh, 4)}


def main() -> int:
    parser = argparse.ArgumentParser(description="Build forecaster profile JSON for production inference.")
    parser.add_argument("--csv", help="Patient CSV with admissionTime and priority/triage_level")
    parser.add_argument("--output", default=str(default_profile_path()))
    args = parser.parse_args()

    if args.csv:
        records = load_records_from_csv(Path(args.csv))
        forecaster = ArrivalForecaster.from_patient_records(records)
    else:
        forecaster = ArrivalForecaster.from_profile_file(default_profile_path())

    thresholds = calibrate_thresholds(forecaster)
    payload = {
        "horizon_hours": forecaster.horizon,
        "description": "Generated by xai/scripts/build_forecaster_profile.py",
        "surge_thresholds": thresholds,
        "rate_by_hour": {str(h): round(forecaster.rate_by_hour[h], 4) for h in range(24)},
        "crit_share_by_hour": {
            str(h): round(forecaster.crit_share_by_hour[h], 4) for h in range(24)
        },
    }

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    print(f"Wrote forecaster profile to {output_path}")
    print(f"Surge thresholds: load>{thresholds['load']}, crit>{thresholds['crit']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
